export type Country = { name: string; code: string; dial: string };

/**
 * Flag image URL for an ISO 3166-1 alpha-2 code. Windows has no flag glyphs in
 * its emoji font, so regional-indicator emoji degrade to bare letters there.
 */
export function countryFlagUrl(code: string): string {
  const normalized = code.trim().toLowerCase();
  if (!/^[a-z]{2}$/.test(normalized)) return '';
  return `https://flagcdn.com/${normalized}.svg`;
}

// ISO country list with dialing codes. Uganda first as the default market.
export const COUNTRIES: Country[] = [
  { name: "Uganda", code: "UG", dial: "+256" },
  { name: "Kenya", code: "KE", dial: "+254" },
  { name: "Tanzania", code: "TZ", dial: "+255" },
  { name: "Rwanda", code: "RW", dial: "+250" },
  { name: "Burundi", code: "BI", dial: "+257" },
  { name: "South Sudan", code: "SS", dial: "+211" },
  { name: "Ethiopia", code: "ET", dial: "+251" },
  { name: "Democratic Republic of the Congo", code: "CD", dial: "+243" },
  { name: "Nigeria", code: "NG", dial: "+234" },
  { name: "Ghana", code: "GH", dial: "+233" },
  { name: "South Africa", code: "ZA", dial: "+27" },
  { name: "Egypt", code: "EG", dial: "+20" },
  { name: "Morocco", code: "MA", dial: "+212" },
  { name: "Algeria", code: "DZ", dial: "+213" },
  { name: "Angola", code: "AO", dial: "+244" },
  { name: "Botswana", code: "BW", dial: "+267" },
  { name: "Cameroon", code: "CM", dial: "+237" },
  { name: "Côte d'Ivoire", code: "CI", dial: "+225" },
  { name: "Malawi", code: "MW", dial: "+265" },
  { name: "Mauritius", code: "MU", dial: "+230" },
  { name: "Mozambique", code: "MZ", dial: "+258" },
  { name: "Namibia", code: "NA", dial: "+264" },
  { name: "Senegal", code: "SN", dial: "+221" },
  { name: "Seychelles", code: "SC", dial: "+248" },
  { name: "Somalia", code: "SO", dial: "+252" },
  { name: "Sudan", code: "SD", dial: "+249" },
  { name: "Tunisia", code: "TN", dial: "+216" },
  { name: "Zambia", code: "ZM", dial: "+260" },
  { name: "Zimbabwe", code: "ZW", dial: "+263" },
  { name: "United Kingdom", code: "GB", dial: "+44" },
  { name: "United States", code: "US", dial: "+1" },
  { name: "Canada", code: "CA", dial: "+1" },
  { name: "Ireland", code: "IE", dial: "+353" },
  { name: "Germany", code: "DE", dial: "+49" },
  { name: "France", code: "FR", dial: "+33" },
  { name: "Netherlands", code: "NL", dial: "+31" },
  { name: "Belgium", code: "BE", dial: "+32" },
  { name: "Denmark", code: "DK", dial: "+45" },
  { name: "Norway", code: "NO", dial: "+47" },
  { name: "Sweden", code: "SE", dial: "+46" },
  { name: "Finland", code: "FI", dial: "+358" },
  { name: "Iceland", code: "IS", dial: "+354" },
  { name: "Spain", code: "ES", dial: "+34" },
  { name: "Portugal", code: "PT", dial: "+351" },
  { name: "Italy", code: "IT", dial: "+39" },
  { name: "Switzerland", code: "CH", dial: "+41" },
  { name: "Austria", code: "AT", dial: "+43" },
  { name: "Poland", code: "PL", dial: "+48" },
  { name: "Czechia", code: "CZ", dial: "+420" },
  { name: "Hungary", code: "HU", dial: "+36" },
  { name: "Romania", code: "RO", dial: "+40" },
  { name: "Bulgaria", code: "BG", dial: "+359" },
  { name: "Greece", code: "GR", dial: "+30" },
  { name: "Croatia", code: "HR", dial: "+385" },
  { name: "Serbia", code: "RS", dial: "+381" },
  { name: "Ukraine", code: "UA", dial: "+380" },
  { name: "Turkey", code: "TR", dial: "+90" },
  { name: "Israel", code: "IL", dial: "+972" },
  { name: "United Arab Emirates", code: "AE", dial: "+971" },
  { name: "Saudi Arabia", code: "SA", dial: "+966" },
  { name: "Qatar", code: "QA", dial: "+974" },
  { name: "Kuwait", code: "KW", dial: "+965" },
  { name: "Oman", code: "OM", dial: "+968" },
  { name: "Bahrain", code: "BH", dial: "+973" },
  { name: "Jordan", code: "JO", dial: "+962" },
  { name: "Lebanon", code: "LB", dial: "+961" },
  { name: "India", code: "IN", dial: "+91" },
  { name: "Pakistan", code: "PK", dial: "+92" },
  { name: "Bangladesh", code: "BD", dial: "+880" },
  { name: "Sri Lanka", code: "LK", dial: "+94" },
  { name: "Nepal", code: "NP", dial: "+977" },
  { name: "China", code: "CN", dial: "+86" },
  { name: "Hong Kong", code: "HK", dial: "+852" },
  { name: "Japan", code: "JP", dial: "+81" },
  { name: "South Korea", code: "KR", dial: "+82" },
  { name: "Singapore", code: "SG", dial: "+65" },
  { name: "Malaysia", code: "MY", dial: "+60" },
  { name: "Indonesia", code: "ID", dial: "+62" },
  { name: "Philippines", code: "PH", dial: "+63" },
  { name: "Thailand", code: "TH", dial: "+66" },
  { name: "Vietnam", code: "VN", dial: "+84" },
  { name: "Australia", code: "AU", dial: "+61" },
  { name: "New Zealand", code: "NZ", dial: "+64" },
  { name: "Brazil", code: "BR", dial: "+55" },
  { name: "Argentina", code: "AR", dial: "+54" },
  { name: "Chile", code: "CL", dial: "+56" },
  { name: "Colombia", code: "CO", dial: "+57" },
  { name: "Peru", code: "PE", dial: "+51" },
  { name: "Mexico", code: "MX", dial: "+52" },
  { name: "Jamaica", code: "JM", dial: "+1876" },
  { name: "Trinidad and Tobago", code: "TT", dial: "+1868" },
  { name: "Russia", code: "RU", dial: "+7" },
  { name: "Kazakhstan", code: "KZ", dial: "+7" },
  { name: "Georgia", code: "GE", dial: "+995" },
  { name: "Armenia", code: "AM", dial: "+374" },
  { name: "Azerbaijan", code: "AZ", dial: "+994" },
];

export const DEFAULT_COUNTRY = COUNTRIES[0]!;

export function findCountry(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code);
}
