import { GuideTravelInformation } from './guide-content.types';

export const UGANDA_TRAVEL_INFORMATION: GuideTravelInformation = {
  introHeading: 'Get Ready',
  intro: 'Travel to Uganda is straightforward. Most friction comes from uncertainty, not complexity.',
  nav: [
    { id: 'visa-information', label: 'Visa Information' },
    { id: 'flights-to-uganda', label: 'Flights and Arrival' },
    { id: 'arrival-getting-around', label: 'Getting Around' },
    { id: 'money-payments', label: 'Money & Payments' },
    { id: 'health-safety', label: 'Health & Safety' },
    { id: 'connectivity-power', label: 'Connectivity & Power' },
    { id: 'what-to-pack', label: 'What to Pack' },
    { id: 'cultural-etiquette', label: 'Cultural Etiquette' },
    { id: 'when-to-travel', label: 'When to Travel' },
  ],
  visaHeading: 'Visa Information',
  visaParagraphs: [
    'Most visitors require a visa to enter Uganda.',
    'Uganda operates an official online e-Visa system, which is the recommended method for most travellers. Applications are submitted in advance and approvals are issued electronically.',
  ],
  officialPortalLabel: 'Official Uganda e-Visa portal',
  officialPortalUrl: 'https://visas.immigration.go.ug',
  atAGlanceHeading: 'At a glance',
  atAGlance: [
    'Visas are applied for online before travel',
    'Passports must be valid for at least 6 months',
    'A Yellow Fever certificate is required on entry',
  ],
  visaFreeHeading: 'Visa-Free Entry',
  visaFreeParagraphs: [
    'Citizens of several African and selected Caribbean and island nations are eligible for visa-free entry to Uganda for short stays.',
    'Visa-free eligibility varies by nationality and length of stay. Travellers should check the Visa-Free Countries page for the full, up-to-date list before travelling.',
  ],
  costsHeading: 'Visa Costs',
  costsIntro: 'Visa fees are standardised by visa type, not nationality.',
  costs: [
    {
      name: 'Single-Entry Tourist Visa',
      price: 'USD $50',
      note: 'Typical cost for most non-visa-free nationalities including UK, EU, US, Canada, Australia',
    },
    {
      name: 'Multiple-Entry Tourist Visa',
      price: 'from USD $100',
      note: 'Issued based on travel history and purpose',
    },
    {
      name: 'East Africa Tourist Visa',
      price: 'USD $100',
      note: 'Valid for Uganda, Kenya, and Rwanda on one visa',
    },
    {
      name: 'Visa-Free Entry',
      price: 'USD $0',
    },
  ],
  costsFootnote: 'Visa fees are paid online and are non-refundable once submitted.',
  flightsHeading: 'Flights and Arrival',
  flightsIntro:
    'International flights arrive via Entebbe International Airport, located on the shores of Lake Victoria.',
  airlineName: 'Uganda Airlines',
  airlineUrl: 'https://ugandairlines.com/',
  airlineSuffix: 'operates direct flights to and from:',
  flightDestinations: [
    'London (Gatwick)',
    'Dubai',
    'Mumbai',
    'Johannesburg',
    'Lagos',
    'Lusaka',
    'Nairobi',
    'Kilimanjaro / Dar es Salaam',
    'Zanzibar',
  ],
  flightsNote:
    'Additional international and regional connections are available via major transit hubs across Europe, the Middle East, and Africa.',
  flightsSchedules:
    'Flight schedules are generally reliable, and arrivals are well managed.',
  airportHeading: 'Airport Arrival',
  airportIntro:
    'Entebbe International Airport is compact and functional. Immigration procedures are orderly, and assistance is available if required.',
  transferBefore: 'Transfers to Kampala typically take',
  transferEmphasis: '30 - 60 minutes',
  transferAfter: ', depending on traffic and time of day.',
  gettingAroundHeading: 'Getting Around',
  transportHeading: 'Transport Within Uganda',
  transportIntro: 'Movement is flexible and informal:',
  transportOptions: [
    { name: 'Ride-hailing apps', detail: 'Operate in major cities' },
    { name: 'Taxis & minibuses', detail: 'Run fixed routes' },
    { name: 'Boda bodas', detail: 'Common for short distances (motorbike taxis)' },
    { name: 'Private drivers', detail: 'Widely used for longer trips and safaris' },
  ],
  transportNote: 'Travel time is best estimated by time of day, not distance.',
  healthHeading: 'Health & Safety',
  healthIntro:
    'Uganda is generally safe for visitors, and for most travellers its day-to-day personal safety feels comparable to navigating any major European or North American city when standard urban precautions are followed.',
  healthColumnHeading: 'Health',
  healthPoints: [
    'Yellow Fever vaccination is mandatory',
    'Routine travel vaccinations are recommended',
    'Private clinics and hospitals operate in major cities',
    'Travel insurance is strongly advised',
  ],
  safetyColumnHeading: 'Personal Safety',
  safetyPoints: [
    'Be aware of your surroundings',
    'Avoid displaying valuables unnecessarily',
    'Use reputable accommodation and transport',
    'Ask locally if unsure — guidance is usually offered freely',
  ],
  moneyHeading: 'Money & Payments',
  moneyIntro: 'The local currency is the Ugandan Shilling (UGX).',
  moneyGuideLabel: 'As a rough guide:',
  fx: [
    { currency: 'USD', unit: 'UGX', lower: '3,800', upper: '4,000' },
    { currency: 'GBP', unit: 'UGX', lower: '4,700', upper: '5,000' },
    { currency: 'EUR', unit: 'UGX', lower: '4,100', upper: '4,400' },
  ],
  moneyParagraphs: [
    'Cash is widely used. Cards are accepted in hotels, malls, and larger restaurants.',
    'Mobile money is common and reliable — used for taxis, food, and everyday payments.',
    'ATMs are available in cities and larger towns.',
  ],
  connectivityHeading: 'Connectivity & Power',
  connectivityColumnHeading: 'Connectivity',
  connectivityPoints: [
    'SIM cards are inexpensive and easy to purchase',
    'Mobile data coverage is strong in cities and along major routes',
    'Wi-Fi is widely available in hotels and cafés',
  ],
  electricityColumnHeading: 'Electricity',
  electricityPoints: [
    'Plug type: UK-style (Type G)',
    'Power supply is generally stable, with occasional outages',
  ],
  packHeading: 'What to Pack (Realistically)',
  packIntro: 'Most visitors do not need specialist equipment.',
  packListLabel: 'Recommended:',
  packItems: [
    'Lightweight clothing',
    'Comfortable walking shoes',
    'A light rain layer',
    'Sun protection',
    'A small day bag',
  ],
  packNote:
    'Specific activities such as trekking or safaris may require additional gear, best handled per itinerary.',
  etiquetteHeading: 'Cultural Etiquette (Quick Guide)',
  etiquettePoints: [
    'Greetings matter; acknowledge people properly',
    'Time is flexible — patience helps',
    'Dress with awareness in social and religious spaces',
    'Ask before taking photographs',
  ],
  etiquetteCloseBefore: 'Using',
  etiquetteMale: 'Ssebo',
  etiquetteMaleNote: '(for a man) or',
  etiquetteFemale: 'Nnyabo',
  etiquetteCloseAfter: '(for a woman) as a respectful form of address is always appropriate.',
  whenHeading: 'When to Travel',
  whenParagraphs: [
    'Uganda is a year-round destination.',
    'Dry periods are generally easier for travel and wildlife viewing. Rainy seasons bring greener landscapes and fewer crowds. There is no single “best” time — only trade-offs.',
  ],
  ctaEyebrow: 'Ready When You Are',
  ctaHeading: 'Once logistics are clear, travel becomes simple.',
  ctaLabel: 'Plan My Trip',
};
